=== Framstag/acousticrules/schema/QualityProfile_Schema.json
{
    "$id": "https://github.com/Framstag/acousticrules/QualityProfile_Schema.json",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "AcousticRules QualityProfile Schema",
    "type": "object",
    "required": ["name", "output_filename", "documentation_filename"],
    "properties": {
        "name": {
            "type": "string"
        },
        "output_filename": {
            "type": "string"
        },
        "documentation_filename": {
            "type": "string"
        },
        "groups": {
            "type": "array",
            "items": {
                "$ref": "#/$defs/group"
            }
        }
    },
    "$defs": {
        "group": {
            "type": "object",
            "required": ["name"],
            "properties": {
                "name": {
                    "type": "string"
                },
                "filters": {
                    "type":"array",
                    "items": {
                        "$ref": "https://github.com/Framstag/acousticrules/Filter_Schema.json"
                    }
                        },
                "modifier": {
                    "type":"array",
                    "items": {
                        "type": "object",
                        "$ref": "https://github.com/Framstag/acousticrules/Modifier_Schema.json"
                    }
                }
            }
        }
    }
}

=== Framstag/acousticrules/Kotlin_QualityProfile.json
{
  "name": "Framstag",
  "output_filename": "Kotlin_QualityProfile.xml",
  "documentation_filename": "Kotlin_QualityProfile.md",
  "groups": [
    {
      "name": "Test Improvements",
      "modifier": [
        {
          "@processor": "ChangeSeverity",
          "reason": "Test improvements are important",
          "from": "INFO",
          "to": "MINOR"
        }
      ]
    },
    {
      "name": "Test Bugs",
      "modifier": [
        {
          "@processor": "ChangeSeverity",
          "reason": "Test bugs are important",
          "from": "MINOR",
          "to": "MAJOR"
        }
      ]
    },
    {
      "name": "Performance",
      "modifier": [
        {
          "@processor": "ChangeSeverity",
          "reason": "We do not want performance relevant problems in our code",
          "from": "MINOR",
          "to": "MAJOR"
        }
      ]
    },
    {
      "name": "Good Code",
      "modifier": [
        {
          "@processor": "ChangeSeverity",
          "reason": "We rank this lower than bugs, performance and security, if it is not CRITICAL or BLOCKER",
          "from": "MAJOR",
          "to": "MINOR"
        }
      ]
    },
    {
      "name": "Obsoletes",
      "modifier": [
        {
          "@processor": "ChangeSeverity",
          "reason": "Our code must be maintainable",
          "from": "MINOR",
          "to": "MAJOR"
        }
      ]
    },
    {
      "name": "Kotlin Improvements",
      "modifier": [
        {
          "@processor": "ChangeSeverity",
          "reason": "Our code should reflect good use of the JDK",
          "from": "MINOR",
          "to": "MAJOR"
        }
      ]
    },
    {
      "name": "Kotlin Bugs",
      "modifier": [
        {
          "@processor": "ChangeSeverity",
          "reason": "Our code must be bug free",
          "from": "MAJOR",
          "to": "BLOCKER"
        }
      ]
    },
    {
      "name": "Spring Improvements",
      "modifier": [
        {
          "@processor": "ChangeSeverity",
          "reason": "Our code should reflect good use of Spring",
          "from": "MINOR",
          "to": "MAJOR"
        }
      ]
    },
    {
      "name": "Spring Bugs",
      "modifier": [
        {
          "@processor": "ChangeSeverity",
          "reason": "Our code must be bug free",
          "from": "MAJOR",
          "to": "BLOCKER"
        }
      ]
    },
    {
      "name": "Bugs",
      "modifier": [
        {
          "@processor": "ChangeSeverity",
          "reason": "Our code must be bug free",
          "from": "MINOR",
          "to": "BLOCKER"
        },
        {
          "@processor": "ChangeSeverity",
          "reason": "Our code must be bug free",
          "from": "MAJOR",
          "to": "BLOCKER"
        },
        {
          "@processor": "ChangeSeverity",
          "reason": "Our code must be bug free",
          "from": "CRITICAL",
          "to": "BLOCKER"
        }
      ]
    },
    {
      "name": "Security",
      "modifier": [
        {
          "@processor": "ChangeSeverity",
          "reason": "Our code must be free of security issues",
          "from": "MINOR",
          "to": "MAJOR"
        }
      ]
    }
  ]
}

=== Framstag/acousticrules/CPP_QualityProfile.json
{
  "name": "Framstag",
  "output_filename": "CPP_QualityProfile.xml",
  "documentation_filename": "CPP_QualityProfile.md",
  "groups": [
    {
      "name": "Test Improvements",
      "modifier": [
        {
          "@processor": "ChangeSeverity",
          "reason": "Test improvements are important",
          "from": "INFO",
          "to": "MINOR"
        }
      ]
    },
    {
      "name": "Test Bugs",
      "modifier": [
        {
          "@processor": "ChangeSeverity",
          "reason": "Test bugs are important",
          "from": "MINOR",
          "to": "MAJOR"
        }
      ]
    },
    {
      "name": "Performance",
      "modifier": [
        {
          "@processor": "ChangeSeverity",
          "reason": "We do not want performance relevant problems",
          "from": "MINOR",
          "to": "MAJOR"
        }
      ]
    },
    {
      "name": "Good Code",
      "modifier": [
        {
          "@processor": "ChangeSeverity",
          "reason": "If it is not too important and is not in another group.",
          "from": "MAJOR",
          "to": "MINOR"
        },
        {
          "@processor": "SetSeverity",
          "reason": "We will not actively work on this",
          "keys": [
            "cpp:S1773"
          ],
          "to": "INFO"
        },
        {
          "@processor": "SetParamForKey",
          "reason": "Our function names are upper case",
          "key": "cpp:S100",
          "param": "format",
          "value": "^[A-Z][a-zA-Z0-9]*$"
        },
        {
          "@processor": "SetParamForKey",
          "reason": "We support modern, wide displays",
          "key": "cpp:S103",
          "param": "maximumLineLength",
          "value": "120"
        },
        {
          "@processor": "SetParamForKey",
          "reason": "We do not have a strict naming scheme for Enums, but at least they all should start upper case",
          "key": "cpp:S2343",
          "param": "format",
          "value": "^[A-Z][a-zA-Z0-9]*$"
        },
        {
          "@processor": "DisableByKey",
          "reason": "We do not restrict the use of // or /* ... */ commands",
          "keys": [
            "cpp:S1708",
            "cpp:S139"
          ]
        },
        {
          "@processor": "DisableByKey",
          "reason": "We are in a library/framework context",
          "keys": [
            "cpp:S5536"
          ]
        },
        {
          "@processor": "DisableByKey",
          "reason": "We do not see this as a real problem, dropping the rule",
          "keys": [
            "cpp:S1915",
            "cpp:S3539",
            "cpp:S1772",
            "cpp:S1774"
          ]
        },
        {
          "@processor": "DisableByKey",
          "reason": "We want to use exceptions for low level errors",
          "keys": [
            "cpp:S1706"
          ]
        },
        {
          "@processor": "DisableByKey",
          "reason": "This rule creates too much noise currently and does not have a good effort/benefit relation",
          "keys": [
            "cpp:S1773"
          ]
        }
      ]
    },
    {
      "name": "Obsoletes",
      "modifier": [
        {
          "@processor": "ChangeSeverity",
          "from": "MINOR",
          "to": "MAJOR"
        }
      ]
    },
    {
      "name": "C++11 Improvements",
      "modifier": [
        {
          "@processor": "ChangeSeverity",
          "reason": "Language based improvements are important, raise severity",
          "from": "MINOR",
          "to": "MAJOR"
        },
        {
          "@processor": "DisableByKey",
          "reason": "Avoiding lambdas is not a helpful warning in our code",
          "keys": [
            "cpp:S1750"
          ]
        }
      ]
    },
    {
      "name": "C++11 Bugs",
      "modifier": [
        {
          "@processor": "ChangeSeverity",
          "from": "MAJOR",
          "to": "BLOCKER"
        }
      ]
    },
    {
      "name": "C++14 Improvements",
      "modifier": [
        {
          "@processor": "ChangeSeverity",
          "reason": "Language based improvements are important, raise severity",
          "from": "MINOR",
          "to": "MAJOR"
        }
      ]
    },
    {
      "name": "C++14 Bugs",
      "modifier": [
        {
          "@processor": "ChangeSeverity",
          "from": "MAJOR",
          "to": "BLOCKER"
        }
      ]
    },
    {
      "name": "C++17 Improvements",
      "modifier": [
        {
          "@processor": "ChangeSeverity",
          "reason": "Language based improvements are important, raise severity",
          "from": "MINOR",
          "to": "MAJOR"
        },
        {
          "@processor": "SetSeverity",
          "reason": "For normal getters this does not have any side-effects, reduce severity",
          "keys": [
            "cpp:S6007"
          ],
          "to": "INFO"
        }
      ]
    },
    {
      "name": "C++17 Bugs",
      "modifier": [
        {
          "@processor": "ChangeSeverity",
          "from": "MAJOR",
          "to": "BLOCKER"
        }
      ]
    },
    {
      "name": "C++ Core Guidelines",
      "modifier": [
        {
          "@processor": "ChangeSeverity",
          "reason": "It is about good practices not bugs, so reduce severity for MAJOR",
          "from": "MAJOR",
          "to": "MINOR"
        },
        {
          "@processor": "SetSeverity",
          "reason": "Important but not critical, reduce severity",
          "keys": [
            "cpp:S3656"
          ],
          "to": "MAJOR"
        }
      ]
    },
    {
      "name": "Misra",
      "modifier": [
        {
          "@processor": "ChangeSeverity",
          "reason": "It is about good practices not bugs, so reduce severity for MAJOR",
          "from": "MAJOR",
          "to": "MINOR"
        },
        {
          "@processor": "DisableByKey",
          "reason": "We do not restrict the use of // or /* ... */ commands",
          "keys": [
            "cpp:S787"
          ]
        },
        {
          "@processor": "DisableByKey",
          "reason": "While a long term goal, this is currently not target  in general",
          "keys": [
            "cpp:S813"
          ]
        },
        {
          "@processor": "DisableByKey",
          "reason": "Too many changes in code to support generally",
          "keys": [
            "cpp:S994"
          ]
        },
        {
          "@processor": "DisableByKey",
          "reason": "Not our rule",
          "keys": [
            "cpp:S1117",
            "cpp:S1005",
            "cpp:S909"
          ]
        },
        {
          "@processor": "SetSeverity",
          "reason": "In principle important, but not our most important problem",
          "keys": [
            "cpp:S997"
          ],
          "to": "MINOR"
        }
      ]
    },
    {
      "name": "Misra C++ 2008",
      "modifier": [
        {
          "@processor": "ChangeSeverity",
          "reason": "It is about good practices not bugs, so reduce severity for MAJOR",
          "from": "MAJOR",
          "to": "MINOR"
        },
        {
          "@processor": "DisableByKey",
          "reason": "Perhaps later but currently to many changes to fix",
          "keys": [
            "cpp:S994"
          ]
        }
      ]
    },
    {
      "name": "Bugs",
      "modifier": [
        {
          "@processor": "ChangeSeverity",
          "from": "MINOR",
          "to": "BLOCKER"
        },
        {
          "@processor": "ChangeSeverity",
          "from": "MAJOR",
          "to": "BLOCKER"
        },
        {
          "@processor": "ChangeSeverity",
          "from": "CRITICAL",
          "to": "BLOCKER"
        }
      ]
    },
    {
      "name": "Security",
      "modifier": [
        {
          "@processor": "ChangeSeverity",
          "from": "MINOR",
          "to": "MAJOR"
        },
        {
          "@processor": "SetParamForKey",
          "reason": "We support C++ and Objective C files with the given postfixes",
          "key": "cpp:S1578",
          "param": "format",
          "value": "^[A-Za-z_-][A-Za-z0-9_-]+\\.(mm|cpp|h|hpp)$"
        },
        {
          "@processor": "DisableByKey",
          "reason": "Too many hits without actual error",
          "keys": [
            "cpp:S864"
          ]
        }
      ]
    }
  ]
}
